DROP DATABASE IF EXISTS employeeTracker_db;
CREATE DATABASE employeeTracker_db;
USE employeeTracker_db;

CREATE TABLE employee (
id INTEGER AUTO_INCREMENT NOT NULL,
PRIMARY KEY(id),
first_name VARCHAR(30),
last_name VARCHAR(30),
role_id INTEGER,
manager_id INTEGER
);

CREATE TABLE role (
id INTEGER AUTO_INCREMENT NOT NULL,
PRIMARY KEY(id),
title VARCHAR(30),
salary DECIMAL(9,2),
department_id INTEGER
);

CREATE TABLE department (
id INTEGER AUTO_INCREMENT NOT NULL,
PRIMARY KEY(id),
name VARCHAR(30)
);

CREATE TABLE Manager (
id INTEGER AUTO_INCREMENT NOT NULL,
PRIMARY KEY(id),
name VARCHAR(30)
);

